### ISSUE TITLE
Implementar Web Service Login

### ISSUE THREAD

**Issue by jorgecasariego** [Enterprise-Solutions/joda#1]
**Parametros**: usuario, password

**Exito**

```json
"{
    ""error"": false,
    ""uid"": ""55fa7220a2c187.50984590"",
    ""user"": {
        ""nombre"": ""Jorge"",
        ""email"": ""jorge@gmail.com""
    }
}"
```

**Error**

```json
"{
    ""error"": true,
    ""error_msg"": ""Usuario o contraseña incorrecta""
}"
```

@joaquinolivera Cuando tengas las url del ws pone como comentario así vemos de probar en alguna app de prueba

**Comment by joaquinolivera** [comment]
localhost:9000/login/:usuario/:password

**Comment by joaquinolivera** [comment]
POST http://192.168.1.121:9000/login?usuario=joaquin&password=123456
