### ISSUE TITLE
Editar contraseña

### ISSUE THREAD

**Issue by jorgecasariego** [Enterprise-Solutions/joda#13]
Esto se debería poder hacer de dos maneras:

1- Desde el telefono donde se envía:
  - Contraseña vieja
  - Contraseña nueva

2. Desde la web
  - Ver si desde la web hace falta agregar la contraseña vieja o directamente se agrega una nueva

**Comment by irisariana** [comment]
Se hizo opcional recibir la contraseña vieja. Además se envía la confirmación de contraseña para comparar en el servidor. Se envía el uid del usuario para identificarlo en el servidor.
