### ISSUE TITLE
Listado de lugares

### ISSUE THREAD

**Issue by jorgecasariego** [Enterprise-Solutions/joda#4]
Datos a mostrar en tabla:
- Lugar
- Dirección

Implementar filtros:
- Usuarios
- Fecha

**Comment by joaquinolivera** [comment]
Se separo en 2 issues, en verdad, uno seria listar lugares, que podría ser filtrado por una distancia establecida o pasada por parámetro, todavía no implementado(se dejo por poca prioridad). El otro es el listado de marcaciones con filtraciones, que ya esta como Issue #7

**Comment by irisariana** [comment]
Fueron agregados filtros para búsqueda, ordenación y paginación. Modificación del formato de respuesta del WS para agregar total de resultados recuperados
