### ISSUE TITLE
Listar Usuarios 

### ISSUE THREAD

**Issue by jorgecasariego** [Enterprise-Solutions/joda#6]
Datos para mostrar en listado
- Nombre
- Apellido
- Documento
- Email
- Usuario
- Activo (indica si es un usuario activo o no)
- Acceso Web (indica si el usuario tiene acceso Web o solo puede acceder a través de la app)

**Comment by irisariana** [comment]
Se agregó la opción de búsqueda por nombre, apellido, email o usuario. 
Paginación
Ordenamiento
