### ISSUE TITLE
Detalle Marcaciones

### ISSUE THREAD

**Issue by jorgecasariego** [Enterprise-Solutions/joda#8]
Datos
- Lugar
- Usuario (Usuario que marco en ese lugar)
- Dirección 
- Cliente
- Fecha
- Hora entrada
- Hora Salida
- Tiempo empleado
- Latitud 
- Longitud

**Comment by joaquinolivera** [comment]
Parece ser igual a listado Marcaciones issue #7 , solo que tiene latitud y longitud. Si es necesario que se retorne un tipo de dato, mas estos atributos, en vez de los que se retornan en issue #7.
